google/nsscache

nss_cache/sources/ldapsource.py, nsscache.conf, nsscache.conf.5
We store our POSIX usernames in a different field than uid.
This is a simple patch just to gauge how this should be done, I'm open to feedback on how you want it handled.
=> Allow for custom uid attribute in passwd ldap source

nss_cache/sources/httpsource.py
Don't hang forever waiting for a broken HTTP server. When the timeout hits, it should trigger a retry, at which point the server will be able to service the request.
=> Set pycurl.TIMEOUT so that an update does not hang waiting indefinitely

nss_cache/sources/consulsource.py, nss_cache/sources/consulsource_test.py, nss_cache/sources/source_factory.py
This adds a new source for Consul's KV store, based on the HTTP source, which uses Consul's API to pull data. User information is assumed to be stored with the following format:
`NAME/ENTRY = 'VALUE'`
ie
`foo/uid = '10'`
`foo/shell = '/bin/bash'`
Entries are fetched recursively so they can be nested under other keys for organization. Currently only passwd and group are implemented (since that was all I had a need for) but it wouldn't be difficult to add in the remaining types. I wanted to see if there was any feedback first.
=> Add new source for Consul

nss_cache/sources/httpsource.py, nss_cache/sources/httpsource_test.py
Servers that don't return a last-modified header will otherwise cause an exception.
=> Set a default empty timestamp string for HTTP responses

nss_cache/sources/ldapsource.py, nss_cache/sources/ldapsource_test.py, nsscache.conf
Following issue #46  - here is something which has been tested and hopefully understandable.  Maybe need to remove the extra config option (maybe just have a different value for the existing option) and whether we really want to postprocess the group data I am not sure since out cn and uid are the same in my organisation but advice welcome.
=> Support uniquemember

nss_cache/sources/ldapsource.py
Without this change retrieving the map sshkey results in the following exception:
(localhost) [~/work/nsscache] nsscache update
Traceback (most recent call last):
File "/usr/bin/nsscache", line 33, in <module>
return_value = nsscache_app.Run(sys.argv[1:], os.environ)
File "/usr/lib/python2.6/site-packages/nss_cache/app.py", line 240, in Run
retval = command_callable().Run(conf=conf, args=args)
File "/usr/lib/python2.6/site-packages/nss_cache/command.py", line 230, in Run
force_lock=options.force_lock)
File "/usr/lib/python2.6/site-packages/nss_cache/command.py", line 303, in UpdateMaps
force_write=force_write)
File "/usr/lib/python2.6/site-packages/nss_cache/update/updater.py", line 265, in UpdateFromSource
force_write, location=None)
File …
=> Provider parameter to SshkeyUpdateGetter in order to fix sshkey map

nss_cache/sources/ldapsource.py
Active Directory apparently serves 'modifyTimeStamp' whereas other implementations serve 'modifyTimeStamp'. We now try both. Three cheers for case-insensitivity.
See Issue #52. There's no simple case-insensitive dictionary lookup in Python, so I just took the KISS route.
=> Issue #52 Fix case-insensitive modifyTimestamp

nss_cache/sources/ldapsource.py
`UpdateGetter.FromLdapToTimestamp` now works with time stamp format `'%Y%m%d%H%M%S.[0-9]*Z'` (used by Active Directory).
Active Directory gives strings like `'20151002151745.0Z'`. The extra `.0` was causing strptime to fail. ldapsource.py will now work with either format.
strptime also has a '%f' for microseconds, but
1. Using that would require converting the decimal value to integer microseconds,
2. My research indicates that strptime doesn't do anything with the microseconds anyway,
3. Plain seconds has worked just fine so far, and
4. My site's AD server only reports a constant '.0' anyway, so we wouldn't gain anything.
=> UpdateGetter.FromLdapToTimestamp Time Stamp Format Fix

nss_cache/update/updater.py
If timestamp_dir (configured in /etc/nsscache.conf) doesn't exist, `nsscache` fails with a sort-of helpful `OSError: [Errno 2] No such file or directory: '/var/lib/nsscache/nsscache-update-Ekxp49'`.
I lost a little time figuring out that I just need to make the directory. This patch makes the directory automatically, simulating `mkdir -p` behavior.
I noticed similar code in `nss_cache/util/timestamps.py` in a method named WriteTimestamp. As far as I can tell, the timestamps.py version is unused. It's pretty close to duplicate code; timestamps.py may have been designed to abstract out the methods as used by updater.py. IDK.
More error text:
````
Traceback (most recent call last):
File "/usr/local/bin/nsscache", line 33, in <module>
return_value = nsscache_app.Run(sys.argv[1:], os.environ) …
```
=> mkdir -p timestamp_dir

nss_cache/caches/caches.py
During certain exceptions, Cache._Rollback would fail to unlink a temp file that didn't yet exist.
Without this fix, the failed file removal obscured the real exception, requiring extra debugging efforts (apparently some exception handlers try to clean up our temp files).
With a maintainer's interest, it might be worth it to define this in some kind of tools file and use it everywhere in place of os.unlink, but this patch is enough for me for now.
Reference: http://stackoverflow.com/questions/10840533/most-pythonic-way-to-delete-a-file-which-may-not-exist
=> Safe file remove

examples/authorized-keys-command.py
Implement a much more useful AuthorizedKeysCommand that does not have
the problems of the original shell version. The new command also
supports ways to filter the keys and do exact matches based on
information from the sshd (eg keytype/fingerprint/keyblob)
Bugs in the old shell version:
- did substring match on usernames instead of exact match
https://github.com/google/nsscache/issues/67
- Failed on keys with characters: [, ], :, ",", "'"
https://github.com/google/nsscache/issues/66
Signed-off-by: Robin H. Johnson <robbat2@gentoo.org>
=> New AuthorizedKeysCommand script

nss_cache/sources/ldapsource.py, nsscache.conf, nsscache.conf.5
A few changes I recorded as I was installing and debugging that should make it easier for future users.
- nsscache.conf    - Changed default cache value to 'nssdb' from 'cache' -- 'cache' is no longer a valid option in nsscache.conf.5 or config.py.
- nsscache.conf.5  - Added ldap_tls_starttls, listed ldap_scope valid options, typo fixes.
- ldapsource.py    - Added synonyms 'onelevel' and 'subtree' to match existing nslcd.conf conventions.
I think I'm almost out of your hair now. :)
=> Documentation and convenience updates

nss_cache/sources/consulsource.py, nss_cache/sources/consulsource_test.py
Currently having a subkey in Consul under, say, a specific user would cause the mapping to try to parse the subkey as another user. That causes exceptions which make the entire update fail.
This change simply ignores any passwd entries that are missing a uid or gid, and any group entries missing a gid. Defaults are already provided for any other missing keys.
=> Ignore subkeys on groups/users in Consul that aren't part of the mapping.

nss_cache/sources/ldapsource.py, nss_cache/sources/ldapsource_test.py
This is a rebase of #61 - I'll add some tests shortly.
=> Add support for paged requests

nss_cache/sources/httpsource.py, nss_cache/sources/httpsource_test.py
HTTP source is currently missing support for sshkey maps. Added the functionality in.
=> Add sshkey maps to http source.

nss_cache/sources/consulsource.py, nss_cache/sources/consulsource_test.py, runtests.py
Allow the consul source module to manage a cache for the shadow database.
With that we can use directly `pam_unix` to do the authentication using what is stored in consul.
=> Add the shadow map to the consul source

.gitignore, nss_cache/sources/ldapsource.py, nss_cache/sources/ldapsource_test.py, nsscache.conf, nsscache.conf.5
Add LDAP client certificate support via the `ldap_tls_certfile`
and `ldap_tls_keyfile` configuration options.  This is useful
for those who wish to enable mTLS authentication with the server.
=> Add LDAP client certificate support

nss_cache/sources/ldapsource.py, nss_cache/sources/ldapsource_test.py, nsscache.conf, nsscache.conf.5
Add a `ldap_override_shell` configuration option that allows the
administrator to override the login shell of each user synchronized from
the LDAP service.  This can be useful on bastion hosts or to enforce
site policy.
=> Add `ldap_override_shell` config option

nss_cache/sources/ldapsource.py
When performing multiple searches in the same area (such as auto fs), if the result is bigger than the page size for the first search, the cookie is not reset for the subsequent search.
=> Fix resetting of cookie

nss_cache/caches/files.py
The parser that got the prefix and suffix were hardcoded to 'nsscache.conf' which ignored the -c parameter. This fetches the path from sys.argv and uses the path specified.
=> Fix files.py ignoring path

nss_cache/caches/nssdb.py
Active Directory can serve usernames with spaces, which Unix can't handle. This caused verification errors when writing the database. Such usernames are now silently ignored.
This is in trying to get nsscache to run on my Ubuntu machine with an Active Directory server.
See Issue #53.
=> Filter out user names with spaces

nss_cache/maps/group.py, nss_cache/sources/ldapsource.py, nss_cache/sources/ldapsource_test.py, nsscache.conf, nsscache.conf.5
Provisionally support nested groups -- for #68 
Caveats:
1. Currently, this will only work with the `--full` update option. Because the entire group map is not available with incremental updates, the updater will not be able to recursively update parent groups when a child group's membership changes
2. This is enabled with the config flag `ldap_nested_groups` under the `[group]` section
=> Nested groups

nsscache
as time.clock() is deprecated, use time.process_time() instead.
=> replaced deprecated time.clock() with time.process_time()

nss_cache/sources/ldapsource.py, nsscache
This is the critical part:
```
for record in data:
for key in record[1]:
if isinstance(record[1][key][0], bytes) and key != 'objectSid':
value = record[1][key][0].decode('utf-8')
record[1][key] = [value]
if self._dn_requested:
merged_records = {'dn': record[0]}
merged_records.update(record[1])
yield merged_records
else:
yield record[1]
```
member list is > 1, so it converts the first member only, we need to check the length of the list, as for members it is not always 1, as for the other attributes. My solution would be:
```
for record in data:
for key in record[1]:
if len(record[1][key]) > 1:
for i, item in enumerate(record[1][key]):
if isinstance(item, bytes) and key != 'objectSid':
value = item.decode('utf-8')
record[1][key][i] = value
else:
if isinstance(record[1][key][0], bytes) and …
```
=> convert all members of a group to string

nss_cache/command_test.py
This fixes a simple test suite error on FreeBSD, because it doesn't have "US/Pacific"
"MST" looks to be common across Linux and BSD.
=> Fix command_test timezone issue on FreeBSD

nss_cache/caches/files.py, nss_cache/caches/files_test.py
Hello,
Following the Python 3 porting efforts, I propose this small fix to be consistent with the other classes of the same file.
This commit convert the strings to bytes before writing them to the cache.
Best regards
=> Ensure that only bytes are written to the cache

nss_cache/sources/ldapsource.py
When we are using `ldap_ad = 1` config, if a user object has not `displayName` property, the map updater fails.
* DisplayName is not an mandatory field in AD and gecos it's only a descritive field en linux
Fix error:
``` 
pw.gecos = obj['displayName'][0]
KeyError: 'displayName'
```
=> Check if displayName exists

nsscache.conf.5
Per https://github.com/google/nsscache/pull/125 add details to the man page related to the new sshkey map added to the s3 source.
=> s3: add sshkey details to man page

nss_cache/sources/httpsource.py, nss_cache/sources/httpsource_test.py, nss_cache/util/curl.py, nsscache.conf.5
PYCurl in python3 requires that you use a bytesIO interface when interacting with it.
The previous PR for Python3 https://github.com/google/nsscache/issues/89 specifically mentions that not all sources were tested.
This adds a better test case to ensure that the http source parsing logic functions as intended.
=> Update http source for required changes related to python3

.github/workflows/auto-review.yml, .github/workflows/automerge.yml, .github/workflows/ci-done.yml, .github/workflows/ci.yml
auto review my own changes, because i'm a single maintainer and still want to
rely on github review checks
automerge dependabot changes
comment CI test results on the change.
=> Update the CI actions.

nss_cache/sources/ldapsource.py
The `uidattr` feature was not considered when writing out the matching
group for a particular user. This change adds this missing feature to
the group logic.
Fixed: #150
=> Respect uidattr when writing out matching group

nss_cache/caches/caches_test.py, nss_cache/caches/files_test.py, nss_cache/lock_test.py, nss_cache/util/timestamps_test.py
Currently this is a rather..brute force approach. While the tests in this PR were fairly straightforward (hopefully!) the leftover tests are ...sometimes challenging.
Two things I'm looking to add in future PRs reduce the complexity here:
- Some kind of test parameterization (there is a fair amount of code duplication in some tests.)
- More fakes instead of mocks (e.g. FakeLock instead of mocking out locks.Pidfile() in places.)
Some of the latter tests also have fairly tight coupling; mostly regarding the use of mocking (e.g. to verify function calls were made as expected.) I'm curious how much effort we want to expend to port these 1:1, vs trying to reduce the coupling.
Aiming for an incremental approach though.
=> WIP: Updating tests to use unittest.mock instead of mox.

nss_cache/sources/gcssource.py, nss_cache/sources/gcssource_test.py, requirements.txt
Based on https://github.com/google/nsscache/blob/main/nss_cache/sources/s3source.py and https://github.com/google/nsscache/blob/main/nss_cache/sources/httpsource.py.
I can't tell exactly what the file format is for files saved in S3, but I want the gcssource to consume "raw" passwd/group/shadow files like how the HTTP source works.
=> feat(gcssource): add support for a GCS bucket source

nss_cache/sources/ldapsource.py, requirements.txt
distutils is now deprecated per https://peps.python.org/pep-0632/
=> Remove `distutils` from `ldapsource`.

nss_cache/sources/gcssource.py
gs:// prefix is used for identifying Cloud Storage objects: https://cloud.google.com/storage/docs/gsutil#syntax
=> Fix log message for when a GCS object is not found.

nss_cache/sources/consulsource.py, nss_cache/sources/consulsource_test.py, nss_cache/sources/gcssource_test.py, nss_cache/sources/httpsource_test.py, nss_cache/sources/ldapsource_test.py, nss_cache/sources/s3source_test.py
=> test: Use mock instead of mox.

.github/workflows/ci.yml
=> ci: Use latest Python now we've stopped using mox.

.github/workflows/ci-done.yml
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
=> ci: Use GITHUB_OUTPUT envvar instead of set-output command

nss_cache/sources/ldapsource.py
in ldapsources, the `except` block should not repeat the KeyError.
```
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/nss_cache/sources/ldapsource.py", line 745, in GetUpdates
obj_ts = self.FromLdapToTimestamp(obj["modifyTimestamp"][0])
~~~^^^^^^^^^^^^^^^^^^^
KeyError: 'modifyTimestamp'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/sbin/nsscache", line 32, in <module>
return_value = nsscache_app.Run(sys.argv[1:], os.environ)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/nss_cache/app.py", line 258, in Run
retval = command_callable().Run(conf=conf, args=args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/nss_cache/command.py", …
```
=> Set fallback timestamp to 0 if LDAP object lacks modifyTimestamp
